import type { PropBox, HandoverRecord } from '@/types';
import { generateId } from './storage';

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString();

const createHandoverRecord = (
  boxId: string,
  data: Partial<HandoverRecord> = {}
): HandoverRecord => ({
  id: generateId(),
  boxId,
  batchNumber: data.batchNumber || 'BATCH-2026-001',
  handoverResult: data.handoverResult || 'completed',
  handoverPerson: data.handoverPerson || '赵管理员',
  receiverPerson: data.receiverPerson || '仓管小王',
  abnormalType: data.abnormalType || '',
  abnormalNote: data.abnormalNote || '',
  processStatus: data.processStatus || 'resolved',
  processNote: data.processNote || '',
  handoverTime: data.handoverTime || yesterday,
  processedAt: data.processedAt || yesterday,
  createdBy: data.createdBy || '赵管理员',
});

export const mockBoxes: PropBox[] = [
  {
    id: generateId(),
    boxNumber: 'A-01',
    contentSummary: '主演服装套装×3、头饰×2',
    scene: '第一场',
    fragileNote: '丝绸面料，需挂放，禁止挤压',
    status: 'pending_pack',
    supplementNote: '需提前熨烫',
    responsiblePerson: '李明',
    riskLevel: 'high',
    needsReturn: true,
    returnNote: '返场时检查头饰完整性',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'A-02',
    contentSummary: '群演服装×8、腰带×8',
    scene: '第一场',
    fragileNote: '普通面料，可折叠',
    status: 'ready_seal',
    supplementNote: '',
    responsiblePerson: '王芳',
    riskLevel: 'low',
    needsReturn: true,
    returnNote: '按角色分装',
    isChecked: true,
    handoverStatus: 'completed',
    handoverPerson: '赵管理员',
    receiverPerson: '仓管小王',
    handoverTime: yesterday,
    handoverNote: '',
    batchNumber: 'BATCH-2026-001',
    abnormalType: '',
    processStatus: 'resolved',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
  },
  {
    id: generateId(),
    boxNumber: 'A-03',
    contentSummary: '道具剑×5、盾牌×3',
    scene: '第二场',
    fragileNote: '泡沫材质，避免重压',
    status: 'pending_return',
    supplementNote: '剑头有磨损需修补',
    responsiblePerson: '张伟',
    riskLevel: 'medium',
    needsReturn: true,
    returnNote: '',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'B-01',
    contentSummary: '玻璃酒杯×12、金属托盘×4',
    scene: '第二场',
    fragileNote: '易碎品，轻拿轻放，气泡膜包裹',
    status: 'pending_pack',
    supplementNote: '备用酒杯×4',
    responsiblePerson: '李明',
    riskLevel: 'high',
    needsReturn: true,
    returnNote: '检查是否有破损',
    isChecked: false,
    handoverStatus: 'abnormal',
    handoverPerson: '赵管理员',
    receiverPerson: '仓管小王',
    handoverTime: yesterday,
    handoverNote: '酒杯破损2只，需更换',
    batchNumber: 'BATCH-2026-001',
    abnormalType: 'damaged',
    processStatus: 'processing',
    processNote: '已通知道具组更换，待重新入库',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
  },
  {
    id: generateId(),
    boxNumber: 'B-02',
    contentSummary: '音响设备、无线麦×6',
    scene: '全场',
    fragileNote: '电子设备，防潮防震',
    status: 'pending_pack',
    supplementNote: '电池×20节',
    responsiblePerson: '刘强',
    riskLevel: 'high',
    needsReturn: true,
    returnNote: '测试所有麦克风',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'C-01',
    contentSummary: '背景画轴×2、挂绳×4',
    scene: '第三场',
    fragileNote: '宣纸材质，防潮',
    status: 'missing_investigate',
    supplementNote: '其中一幅有撕裂需修复',
    responsiblePerson: '王芳',
    riskLevel: 'medium',
    needsReturn: true,
    returnNote: '确认修复状态',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'C-02',
    contentSummary: '灯光滤色片×20',
    scene: '全场',
    fragileNote: '玻璃制品，易碎',
    status: 'pending_return',
    supplementNote: '',
    responsiblePerson: '刘强',
    riskLevel: 'medium',
    needsReturn: true,
    returnNote: '按颜色分类归位',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'D-01',
    contentSummary: '化妆用品×1套',
    scene: '全场',
    fragileNote: '液体化妆品防漏',
    status: 'ready_seal',
    supplementNote: '补发胶×2',
    responsiblePerson: '陈丽',
    riskLevel: 'low',
    needsReturn: true,
    returnNote: '检查保质期',
    isChecked: true,
    handoverStatus: 'completed',
    handoverPerson: '钱管理员',
    receiverPerson: '仓管小李',
    handoverTime: yesterday,
    handoverNote: '',
    batchNumber: 'BATCH-2026-001',
    abnormalType: '',
    processStatus: 'resolved',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
  },
  {
    id: generateId(),
    boxNumber: 'D-02',
    contentSummary: '假发套×5、发网×20',
    scene: '第一场',
    fragileNote: '人造毛发，避免高温',
    status: 'pending_pack',
    supplementNote: '',
    responsiblePerson: '陈丽',
    riskLevel: 'low',
    needsReturn: true,
    returnNote: '',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'A-01',
    contentSummary: '重复箱号测试数据',
    scene: '第二场',
    fragileNote: '',
    status: 'pending_pack',
    supplementNote: '',
    responsiblePerson: '张伟',
    riskLevel: 'low',
    needsReturn: false,
    returnNote: '',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: generateId(),
    boxNumber: 'E-01',
    contentSummary: '古董花瓶×1',
    scene: '第三场',
    fragileNote: '贵重易碎品，专人搬运',
    status: 'pending_pack',
    supplementNote: '保险已投保',
    responsiblePerson: '李明',
    riskLevel: 'high',
    needsReturn: true,
    returnNote: '',
    isChecked: false,
    handoverStatus: 'abnormal',
    handoverPerson: '赵管理员',
    receiverPerson: '仓管小王',
    handoverTime: yesterday,
    handoverNote: '花瓶底部发现细微裂纹',
    batchNumber: 'BATCH-2026-001',
    abnormalType: 'damaged',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
  },
  {
    id: generateId(),
    boxNumber: 'E-02',
    contentSummary: '大型布景零件×15',
    scene: '第三场',
    fragileNote: '木质结构，避免碰撞',
    status: 'pending_return',
    supplementNote: '需扳手组装',
    responsiblePerson: '张伟',
    riskLevel: 'medium',
    needsReturn: true,
    returnNote: '清点零件数量',
    isChecked: false,
    handoverStatus: 'pending',
    handoverPerson: '',
    receiverPerson: '',
    handoverTime: '',
    handoverNote: '',
    batchNumber: '',
    abnormalType: '',
    processStatus: 'pending',
    processNote: '',
    handoverRecords: [],
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
];

mockBoxes.forEach((box) => {
  if (box.handoverStatus !== 'pending') {
    const record = createHandoverRecord(box.id, {
      batchNumber: box.batchNumber,
      handoverResult: box.handoverStatus,
      handoverPerson: box.handoverPerson,
      receiverPerson: box.receiverPerson,
      abnormalType: box.abnormalType,
      abnormalNote: box.handoverNote,
      processStatus: box.processStatus,
      processNote: box.processNote,
      handoverTime: box.handoverTime || yesterday,
      processedAt: box.handoverTime || yesterday,
      createdBy: box.handoverPerson,
    });
    box.handoverRecords = [record];
  }
});
